{{- range .Values.pvs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
    {{- toYaml $.Values.volumeAccessModes | nindent 4 }}
  nfs:
    path: /exports/{{ .name }}
    server: {{ .nfsServer }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy }}
  {{- if $.Values.storageClass }}
  storageClassName: {{ $.Values.storageClass }}
  {{- end }}
---
{{- end }}
