apiVersion: v1
kind: Service
metadata:
  name: {{ include "dispatcher.fullname" . }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    {{- include "dispatcher.selectorLabels" . | nindent 4 }}
