# Default values for remote-segmenter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: RollingUpdate

image:
  repository: lunityounghwan/remote-segmenter-dispatcher
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: "16"
    memory: "8Gi"
    ephemeral-storage: "10Gi"
  requests:
    cpu: "16"
    memory: "8Gi"
    ephemeral-storage: "10Gi"
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  # targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40

# Additional volumes on the output Deployment definition.
volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: data-pvc
  - name: tmp-volume
    persistentVolumeClaim:
      claimName: tmp-pvc

volumeMounts:
  - name: data-storage
    mountPath: /mnt/data
    readOnly: false  # Set to false if you need write access
  - name: tmp-volume
    mountPath: /tmp
    readOnly: false  # Set to false if you need write access


nodeSelector: {}

tolerations: []

affinity: {}

nfsServer: "10.77.57.194" # Change this to the IP address of your NFS server

pvs:
  - name: data-pv
    storage: 100Gi
    reclaimPolicy: Retain
    nfsServer: {{ .Values.nfsServer }}
    accessModes:
      - ReadWriteMany
  - name: tmp-pv
    gcePersistentDisk: tmp-disk
    storage: 100Gi
    reclaimPolicy: Delete
    nfsServer: {{ .Values.nfsServer }}
    accessModes:
      - ReadWriteMany
pvcs:
  - name: data-pvc
    storage: 100Gi
    volumeName: data-pv
  - name: tmp-pvc
    storage: 100Gi
    volumeName: tmp-pv


volumeAccessModes:
  - ReadWriteMany

storageClass: ""

knativeService:
  autoscaling:
    initialScale: 2
    target: 2
    maxScale: 16
    scaleDownDelay: "10m"
  nodeSelector:
    accelerator: "nvidia-tesla-t4"
  image:
    repository: "lunityounghwan/remote-segmenter-patch-server"
    tag: "v0.1.0"
  resources:
    limits:
      gpu: "1"
  containerPort: 8000
